### ISSUE TITLE
bug(cache): Buggy Discord Caching

### ISSUE THREAD

**Issue by SpaceLeft** [ParadiseBotLists/Website#3]
![Capture](https://user-images.githubusercontent.com/40790870/162580023-35b97f03-1646-4695-89c4-47b28811f6d5.PNG)

**Comment by TheRealToxicDev** [comment]
@Connor200024 do you remember how to fix this issue?

**Comment by SpaceLeft** [comment]
any help?

**Comment by Connor200024** [comment]
I am sorting this via discord.
