### ISSUE TITLE
support(mongo): Connection String Location

### ISSUE THREAD

**Issue by RobloxGithub** [ParadiseBotLists/Website#4]
Where is mongodb

**Comment by TheRealToxicDev** [comment]
https://github.com/ParadiseBotLists/Website/blob/4b9731b05e19816c26b243553655272bcebdf376/events/message.js#L7

> Where is mongodb

**Comment by RobloxGithub** [comment]
Thanks does paradisebots still exist or I can take?

**Comment by TheRealToxicDev** [comment]
> Where is mongodb

![8CECEC43-AC66-4474-B912-1DDB975E530D](https://user-images.githubusercontent.com/59587139/167313364-5f91de31-3586-42d4-b226-f7b0b7b1b215.jpeg)
