### ISSUE TITLE
support(discord): Client Callback Setup

### ISSUE THREAD

**Issue by RobloxGithub** [ParadiseBotLists/Website#5]
Callback? How to do

**Comment by TheRealToxicDev** [comment]
> Callback? How to do

This can be achieved in the config

https://github.com/ParadiseBotLists/Website/blob/4b9731b05e19816c26b243553655272bcebdf376/config.js#L3

Set the ID, Client Secret and Domain.

if you are local hosting the domain should be:
`http://localhost:PORT/callback`

In production:
`https://domain.com/callback`

**Comment by RobloxGithub** [comment]
Ty
