### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by RobloxGithub** [ParadiseBotLists/Website#6]
Can I re-claim the site?

**Comment by TheRealToxicDev** [comment]
> Can I re-claim the site?

Paradise is a Limited Liability Company owned and operated by me so no lol. Our website is not permanently shut down.

**Comment by RobloxGithub** [comment]
> > Can I re-claim the site?
> 
> Paradise is a Limited Liability Company owned and operated by me so no lol. Our website is not permanently shut down and will return in the future with new styling and features.

Re-question:.

But can I re-claim old code

**Comment by TheRealToxicDev** [comment]
> > > Can I re-claim the site?
> > 
> > 
> > Paradise is a Limited Liability Company owned and operated by me so no lol. Our website is not permanently shut down and will return in the future with new styling and features.
> 
> Re-question:.
> 
> But can I re-claim old code

I’ve already said NO lol
