### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by RobloxGithub** [ParadiseBotLists/Website#7]
how to fix this![Screenshot_2022-05-09-13-53-37-076_com.android.chrome.jpg](https://user-images.githubusercontent.com/79148975/167404840-b14c9ad9-054b-40bc-83a1-9dfbedf419a3.jpg)![Screenshot_2022-05-09-12-28-52-877_com.android.chrome.jpg](https://user-images.githubusercontent.com/79148975/167404853-e5a5d500-de6c-484a-b4de-2c1326039875.jpg)

**Comment by TheRealToxicDev** [comment]
> how to fix this![Screenshot_2022-05-09-13-53-37-076_com.android.chrome.jpg](https://user-images.githubusercontent.com/79148975/167404840-b14c9ad9-054b-40bc-83a1-9dfbedf419a3.jpg)![Screenshot_2022-05-09-12-28-52-877_com.android.chrome.jpg](https://user-images.githubusercontent.com/79148975/167404853-e5a5d500-de6c-484a-b4de-2c1326039875.jpg)

Add the missing ) like it tells you too 🤷

**Comment by RobloxGithub** [comment]
But its added

pon, 9. svi 2022. 15:57 Toxic Dev ***@***.***> je napisao:

**Comment by TheRealToxicDev** [comment]
> But its added pon, 9. svi 2022. 15:57 Toxic Dev ***@***.***> je napisao:

Its not. it clearly says theres one missing. 🤷🏻 should be 

`app.listen(config.port, null, null, () => console.log(`Dashboard is ready at: ${config.port}`));`
