### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by RobloxGithub** [ParadiseBotLists/Website#8]
I did add ) so why it doesn't work ir where i should set it t

**Comment by TheRealToxicDev** [comment]
> I did add ) so why it doesn't work ir where i should set it t

Its not. it clearly says theres one missing. 🤷🏻 should be 

app.listen(config.port, null, null, () => console.log(`Dashboard is ready at: ${config.port}`));

**Comment by RobloxGithub** [comment]
Still error
